Add support for specification of a prefered profile
Behat/Behat pull request #1334
Opened 2021-02-14 05:32 UTC by andrewnicols

In many situations it is desirable to have a specific profile that is
used when none is specified, however because of the way in which all
profiles inherit from the `default` profile, this is not currently
possible.

For example, if you have different MinkExtension configurations for a
range of different browsers, then each browser may only be specified in
its own profile. This works well, but often you will want to specify a
default browser configuration.

To achieve this you may think that you can set the Extension
configuration for your preferred browser into the `default` profile, but
this means that all other profiles will include this configuration, and
may not work as expected.

This change introduces the concept of a preferred profile, which is the
profile which will be used unless the `--profile` CLI argument is
provided to override it.

This means that if you have profiles for chrome, headlesschrome,
firefox, headlessfirefox, edge, and headlessedge, you can choose to
specify a preferred profile of `headlesschrome`, which will be used
unless you explicitly set the `--profile` argument when running behat.

2021-02-15 01:45 UTC, andrewnicols commented
The failures above seem to be reproducible against master, before my patch is applied.

2021-02-22 03:58 UTC, andrewnicols commented
Most of the tests are now passing with the exception of Scrutinizer. Not sure how best to solve that one.

Any chance of a review on this change?

2021-03-12 05:51 UTC, andrewnicols commented
Is there anything that I can do to help get this over the line?

It's a real cause of frustration for developers on our project.

2021-06-01 00:34 UTC, andrewnicols commented
Hi @stof, @everzet, @ciaranmcnulty ,

I'm just wondering if there's any chance that we might see this merged at some point, or if there's anything that I can do to help things along.

All tests are passing, and there's a real and valid use-case for it.

Thanks

2021-07-16 13:35 UTC, andrewnicols commented
Pinging @stof, @ciaranmcnulty, @everzet again.

This issue has been sat waiting for attention for 5 months now. What can we do to help?

2022-06-30 14:08 UTC, ciaranmcnulty commented
Can you take the changelog entry out please? (I need to change the guidance on that)

I'm not sure about the use case - this is to avoid having to type `--profile` each time?

2024-10-20 15:23 UTC, carlos-granados requested changes
@andrewnicols,  as suggested by @ciaranmcnulty, could you please remove the changes to CHANGELOG.md? This is handled separately. Otherwise it looks good to me

2024-10-26 12:52 UTC, carlos-granados approved these changes
@andrewnicols I rebased your change and removed the change to the CHANGELOG file. It all looks OK now for me

2024-10-26 22:49 UTC, acoulton approved these changes
LGTM, thanks for the contribution @andrewnicols

2024-10-26 22:49 UTC, merged