Allow test selection to be empty
Behat/Behat pull request #1420
Opened 2023-01-11 12:48 UTC by Kingdutch

In our CI we split out test jobs based on folder. Additionally we run each `.feature` file individually so we can create output test groups. However, due to how we've arranged our tags and our test matrices it could be that Behat is called with a path to a file that has all tests excluded using a tag.

The change in this PR provides an option to mute this error and prevent a CI from failing when no tests were executed deliberately.

Fixes #1389

2024-10-19 23:24 UTC, acoulton requested changes
This feels risky to me - personally I'd want my tooling to explicitly skip combinations of files / tags that were expected not to run any tests. Otherwise there's a chance at some point behat stops finding tests (due to changes in the project or e.g. a behat upgrade) but goes green without running anything.

However, happy to merge it as an opt-in if it's useful to others.

But I find `--allow-empty` a bit unclear. Could it be `--allow-no-tests` instead?

2024-10-20 14:38 UTC, carlos-granados requested changes

2024-10-20 14:38 UTC, carlos-granados commented on src/Behat/Testwork/Tester/Cli/ExerciseController.php
> +              'Will not fail if no specification are found.'
Should be "if no specifications are found"

2025-03-05 08:28 UTC, Kingdutch commented
@acoulton @carlos-granados Thanks for your feedback! Took me a bit of time to get to it. I've renamed the flag to `--allow-no-tests`, that's a clearer name. I've also fixed the description to make `specifications` plural.

2025-03-05 09:01 UTC, carlos-granados approved these changes
Thanks @Kingdutch

2025-03-10 20:15 UTC, acoulton approved these changes
Great, thanks for coming back to this @Kingdutch

2025-03-10 20:15 UTC, merged