DX: better output for wrong status code or unexpected output
Behat/Behat pull request #1532
Opened 2024-11-12 22:52 UTC by jdeniau

Fixes #1522

### Then it should pass/fail with: + expected status code + wrong output

![image](https://github.com/user-attachments/assets/44816f29-81d0-4359-b34c-821d1ec624d3)

### Then it should pass/fail with: + wrong status code + wrong output

![image](https://github.com/user-attachments/assets/d9ccb989-0c8a-4fbd-865b-30a0aa957c1b)

### Then it should pass/fail with: + wrong status code + expected output

![image](https://github.com/user-attachments/assets/c4fe56c4-b0f9-4c9e-966b-4be9ce381001)

### Then the output should contain with unexpected value

![image](https://github.com/user-attachments/assets/524b6944-ef03-4a51-91f9-2c48b869d895)

### Then it should pass/fail

![image](https://github.com/user-attachments/assets/fa383814-aa92-425a-acf1-36e9e2682d06)

2024-11-13 14:52 UTC, carlos-granados requested changes
Mostly looking good, just a few tiny comments

2024-11-13 14:52 UTC, carlos-granados commented on features/bootstrap/FeatureContext.php
> +    public function exitCodeIsCorrect(string $success): bool
I don't think this function needs to be public

2024-11-13 14:52 UTC, carlos-granados commented on features/bootstrap/FeatureContext.php
> +
And this one as well

2024-11-15 07:54 UTC, acoulton approved these changes
@jdeniau thanks - this looks great and will be very helpful, I don't have anything to add to @carlos-granados changes

2024-11-15 08:11 UTC, jdeniau commented
@carlos-granados this is updated

2024-11-15 08:19 UTC, carlos-granados approved these changes
Thanks @jdeniau !

2024-11-15 08:19 UTC, merged