Php config imports
Behat/Behat pull request #1538
Opened 2024-11-18 16:43 UTC by loic425

Referenced issue : #1539 
Based on #1537 

Several proposals for this importing feature.

**Use variadic**
```php
use Behat\Config\Config;

$config = new Config();
$config->import('first_file.php', 'second_file.php', ...);
```

If we have too much files to imports, using multiple lines is still possible.

```php
use Behat\Config\Config;

$config = new Config();
$config->import(
    'first_file.php', 
    'second_file.php', 
    ...,
    ...,
    'another_file.php', 
);
```

**Use array**
```php
use Behat\Config\Config;

$config = new Config();
$config->import(['first_file.php', 'second_file.php', ...]);
```

**[Current state of this PR] Use simple way (and even support array or string at the same time)**
```php
use Behat\Config\Config;

$config = new Config();
$config
    ->import('first_file.php') 
    ->import('second_file.php')
    // ...
;
```

OR

```php
use Behat\Config\Config;

$config = new Config();
$config->import(['first_file.php', 'second_file.php', ...]) ;
```

One of the benefits of this way is that we can add optional arguments later.

```php
public function import(string|array $resource, string $type = null, bool $ignoreErrors = false): self
```

Moreover, we need to think about an implementation for importing using a pattern. 

**Using pattern**
```php
use Behat\Config\Config;

$config = new Config();
$config->import('config/../..php');
```

**Symfony way**

_Dependency Injection_
https://github.com/symfony/symfony/blob/7.3/src/Symfony/Component/DependencyInjection/Loader/Configurator/ContainerConfigurator.php#L64

_Routing_
The routing way is also interesting
https://github.com/symfony/routing/blob/7.1/Loader/Configurator/RoutingConfigurator.php#L37

2024-11-18 16:45 UTC, loic425 commented on src/Behat/Config/Config.php
> +    public function import(string $file): self
Could be interesting...

```suggestion
    public function import(... string $files): self
```

2024-11-18 22:43 UTC, acoulton requested changes
Obviously we need to look at #1537 first, but probably worth considering the overall feature / plan for future direction

2024-11-18 22:43 UTC, acoulton commented on src/Behat/Config/Config.php
> +            $this->settings['imports'][] = $file;
I might have missed something, but if the `->import()` method just adds keys/values to the array you are already defining in the file, why wouldn't you just do that inline?

E.g. 
```
return new Config([
  'imports' => [
    __DIR__.'/other-config.php'
  ],
  // Other values 
])
```

2024-11-20 13:44 UTC, loic425 commented on src/Behat/Config/Config.php
> +    public function import(string ...$files): self
I think this should be better without variadic thing or I should remame the method "imports" instead.
```suggestion
    public function import(string $file): self
```

2024-11-22 11:19 UTC, acoulton commented
I think my preference would be:
* For explicit files, a variadic e.g. `import(string ...$imports)`
* For pattern matching, a separate `importMatching(string $pattern)` - if you want multiple patterns, you call it multiple times. Possibly with something like `importMatching(string $pattern, bool $throwIfNoMatches = true)` to give people control / safety over what happens if nothing matches the pattern.

2024-11-23 10:15 UTC, loic425 commented
> I think my preference would be:
> 
>     * For explicit files, a variadic e.g. `import(string ...$imports)`
> 
>     * For pattern matching, a separate `importMatching(string $pattern)` - if you want multiple patterns, you call it multiple times. Possibly with something like `importMatching(string $pattern, bool $throwIfNoMatches = true)` to give people control / safety over what happens if nothing matches the pattern.

I've removed the two methods way from the proposal and added a simple one based on Symfony routing configurator.

2024-11-26 11:11 UTC, loic425 commented on src/Behat/Config/Config.php
> +    public function import(string|array $resource): self
```suggestion
    /** @param string|string[] $resource **/
    public function import(string|array $resource): self
```

2024-11-26 14:41 UTC, carlos-granados approved these changes
Looking good to me, thanks @loic425

2024-11-26 15:22 UTC, loic425 commented
@acoulton Is the current state ok for you.
I've simplified with a single method with string or array of string.

2024-11-27 09:45 UTC, acoulton commented on src/Behat/Config/Config.php
> +        $resources = is_string($resource) ? [$resource] : $resource;
I would personally use a variadic here, it gives us (and users) strict typing out of the box including protecting against unexpected/unused extra arguments, keeps our own code as thin as possible, and therefore reduces any risk of edge cases.

As a user, the syntax `->import('one.php', 'two.php')` is also cleaner and easier to format IMO than having the redundant array braces.

I know there are other tools out there that do `string|string[]` but my sense is those are interfaces that were designed before variadics were available and so they're tied to them. I don't think we should be, unless there's a reason not to use a variadic that I haven't thought of?

2024-11-28 09:09 UTC, acoulton commented on src/Behat/Config/Config.php
> +        $resources = is_string($resource) ? [$resource] : $resource;
Fair enough, makes sense.

2024-11-28 09:09 UTC, acoulton approved these changes

2024-11-28 09:09 UTC, merged