#1565 fix: parse parent callees when using attributes
Behat/Behat pull request #1567
Opened 2024-12-13 10:06 UTC by fmatsos

As mentioned by @stof here: https://github.com/Behat/Behat/issues/1565#issuecomment-2535430466, `AttributeContextReader` was incomplete compared to its annotation equivalent.

We add here the missing code to retrieve parent callees, like annotations do.

2024-12-13 10:14 UTC, loic425 commented on src/Behat/Behat/Context/Reader/AttributeContextReader.php
> +
```suggestion
            );
```

2024-12-13 10:15 UTC, loic425 commented on src/Behat/Behat/Context/Reader/AttributeContextReader.php
> +
```suggestion
```

2024-12-13 10:20 UTC, fmatsos commented
@carlos-granados @acoulton when you have some time to check this one 😄

2024-12-13 10:54 UTC, fmatsos commented on features/definitions_override.feature
> +          #[Then(':token should not be :value')]
Done!

2024-12-16 10:32 UTC, acoulton requested changes
The implementation LGTM thanks, just a couple of comments on the tests.

2024-12-16 10:32 UTC, acoulton commented on features/definitions_override.feature
> +  Using step definitions as annotations
I would add this to the `I need to be able to override definition methods using annotations` to keep the `In order to .. as a ... I need to...` three-line structure

2024-12-16 10:32 UTC, acoulton commented on features/definitions_override_attributes.feature
> +  I need to be able to override definition methods
```suggestion
  In order to fine-tune definitions defined in parent classes
  As a step definitions developer
  I need to be able to override definition methods using step definition attributes
```

2024-12-16 10:32 UTC, acoulton commented on features/definitions_override_attributes.feature
> +      """
We should probably also have a case for what happens if the parent has an annotation and the child has an attribute (which might occur if a project migrates to attributes but is still using a third-party library that uses annotations)?

I think so long as that still ends up with both definitions attached, we can probably skip the case for parent attribute / child annotation which will presumably behave the same.

2024-12-18 13:20 UTC, fmatsos commented
> Great, thanks

You're welcome! 😄 

And sorry for the confusion with the title of PR. My English is not always good and understandable ahah!

2024-12-18 13:25 UTC, carlos-granados approved these changes
Looking good, thanks @fmatsos

2024-12-18 13:28 UTC, merged

2024-12-18 14:02 UTC, fmatsos commented on src/Behat/Behat/Context/Reader/AttributeContextReader.php
> +    public function readParentCallees(
I'll fix it here: https://github.com/Behat/Behat/pull/1564 👍🏻