ci: #1405 do not run ci builds for some specific files
Behat/Behat pull request #1582
Opened 2024-12-28 16:36 UTC by codisart

fix latest php version for matrix strategy

2025-01-02 18:05 UTC, carlos-granados requested changes

2025-01-02 18:05 UTC, carlos-granados commented on .github/workflows/build.yml
> +      - 'CHANGELOG.md'
Perhaps we could just use '- '**.md' to cover all markdown files?

2025-01-02 18:05 UTC, carlos-granados commented on .github/workflows/build.yml
> +          - php: 8.4
I think it is best if this job remains with PHP 8.2

2025-01-05 20:20 UTC, codisart commented on .github/workflows/build.yml
> +      - 'CHANGELOG.md'
better idea ! 

done.

2025-01-05 20:20 UTC, codisart commented on .github/workflows/build.yml
> +          - php: 8.4
done

2025-01-06 11:25 UTC, acoulton approved these changes
LGTM, thanks!

2025-01-09 16:25 UTC, carlos-granados approved these changes
Thanks @codisart

2025-01-09 16:25 UTC, merged